application: hew2017-iw13a627
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: *.html
  static_files: *.html
  upload: *.html

- url: /css
  static_dir: css

- url: /images
  static_dir: images
